export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  PUBLIC = 'ROLE_PUBLIC',
  NEA_ADMIN = 'ROLE_NEA_ADMIN',
  ACCOUNT_ADMIN = 'ROLE_ACCOUNT_ADMIN',
  SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
  CHANNEL_PATNER = 'CHANNEL_PATTNER',
}
