export enum USER_ROLE {
  SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
  NEA_ADMIN = 'ROLE_NEA_ADMIN',
  ADMIN = 'ROLE_ACCOUNT_ADMIN',
  FRANCHISE = 'ROLE_ACCOUNT_ADMIN',

  USER = 'ROLE_USER',
  PUBLIC = 'ROLE_PUBLIC',
  CHANNEL_PATNER = 'CHANNEL_PATTNER',
}
