export enum USER_ROLE {
  SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
  ADMIN = 'ROLE_NEA_ADMIN',
  FRANCHISE = 'ROLE_ACCOUNT_ADMIN',

  // USER = 'ROLE_USER',
  // PUBLIC = 'ROLE_PUBLIC',
  // CHANNEL_PATNER = 'CHANNEL_PATTNER',
}
